version: 0.2

env:
  variables:
    S3_BUCKET: "sam-demo-bucket-cs"
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - curl -sSL https://install.python-poetry.org | python3 -
      - export PATH="$HOME/.local/bin:$PATH"
  pre_build:
    commands:
      - poetry install
  build:
    commands:
      - sam build --use-container
  post_build:
    commands:
      - sam package --s3-bucket $S3_BUCKET --output-template-file packaged.yaml

artifacts:
  type: zip
  files:
    - packaged.yaml
